MixLoRA vs LoRA on Spivavtor GEC

In [1]:
import os
from kaggle_secrets import UserSecretsClient

secrets = UserSecretsClient()
def secret(name):
    try:
        return secrets.get_secret(name)
    except Exception:
        return None

for name in ["WANDB_API_KEY", "HF_TOKEN"]:
    if value := secret(name):
        os.environ[name] = value

REPO_DIR = "/kaggle/working/ai500-labs"
BRANCH = "main"
token = secret("GITHUB_TOKEN")
url = f"https://{token}@github.com/PavloKhomenko/ai500-labs.git" if token else "https://github.com/PavloKhomenko/ai500-labs.git"

In [2]:
# the token is passed only on the command line, origin keeps the public url (/kaggle/working gets saved)
if os.path.exists(REPO_DIR):
    !git -C {REPO_DIR} pull -q {url} {BRANCH}
else:
    !git clone -q -b {BRANCH} {url} {REPO_DIR}
    !git -C {REPO_DIR} remote set-url origin https://github.com/PavloKhomenko/ai500-labs.git
!git -C {REPO_DIR} log --oneline -1

c824dd7 (HEAD -> main, origin/main, origin/HEAD) part 3 setup

In [3]:
# versions from lab-1/uv.lock; torch stays Kaggle's CUDA build
!pip install -q "transformers==5.18.0" "datasets==5.1.0" "accelerate==1.15.0" "peft==0.21.2" \
    "huggingface-hub==1.33.0" "wandb==0.30.0" "tabulate==0.10.0" "pyyaml==6.0.3" "sacrebleu==2.6.0"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 95.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 604.4/604.4 kB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 16.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 835.4/835.4 kB 28.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 846.4/846.4 kB 23.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.1/26.1 MB 68.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.3/60.3 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.1/140.1 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.3/206.3 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 MB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 6.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.48.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 2.7.1 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.45.1 which is incompatible.
google-adk 2.7.1 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.45.1 which is incompatible.

In [4]:
import sys
sys.path.insert(0, f"{REPO_DIR}/lab-1/src")

import pandas as pd
import torch
import transformers
from transformers import AutoModelForCausalLM, AutoTokenizer

from lab1.common import load_config, out_dir
from lab1.part2 import wandb_log as wl
from lab1.part3.mixlora import Adapter
from lab1.part3.sft import Part3Report, SFTTrainer, SpivavtorData
%matplotlib inline

cfg = load_config()
p3 = cfg["part3"]
device = torch.device("cuda")
env = {"torch": torch.__version__, "transformers": transformers.__version__, "gpu": torch.cuda.get_device_name()}
print(env)
p3_dir = out_dir(cfg, "part3")

def start_run(name, job_type, **extra):
    return wl.init_run(cfg, name, job_type, config={**p3, **env, **extra}, group="part3",
                       project=cfg["wandb"]["part3_project"])

def load_base():
    return AutoModelForCausalLM.from_pretrained(p3["model"], dtype=torch.float16).to(device)

{'torch': '2.11.0+cu128', 'transformers': '5.18.0', 'gpu': 'Tesla T4'}

In [5]:
tok = AutoTokenizer.from_pretrained(p3["model"])
data = SpivavtorData(tok, p3, seed=cfg["seed"])
data.check_masking()
data.check_disjoint()

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

README.md:   0%|          | 0.00/1.63k [00:00<?, ?B/s]

train.jsonl: reconstructing file:   0%|          |  0.00B / 27.9MB

train.jsonl: downloading bytes:           |  0.00B

val.jsonl:   0%|          | 0.00/3.08M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/62784 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/6976 [00:00<?, ? examples/s]

{'train': 4000, 'val': 300, 'test': 300}
masking ok: 'І завжди у мене була якась “велика ціль”, на яку я відкладав гроші протягом місяців, а іноді навіть років.<|im_end|>'
splits disjoint: {'train': 4000, 'val': 300, 'test': 300}

In [6]:
!pip uninstall -q -y torchao

In [7]:
# checks in fp32 (fresh model each time, no deepcopy: T4 memory)
def load_fp32():
    return load_base().float().eval()

ids = torch.tensor([data.val[0]["ids"]], device=device)
base = load_fp32()
with torch.no_grad():
    ref = base(input_ids=ids).logits.float()
del base

checks = {}
for name, make in {"mixlora-none": lambda m: Adapter.mixlora(m, p3, "none"),
                   "mixlora-bias": lambda m: Adapter.mixlora(m, p3, "bias"),
                   "lora": lambda m: Adapter.lora(m, p3["lora_rank"])}.items():
    ad = make(load_fp32())
    ad.check_param_count()
    ad.check_identity(ids, ref)
    ad.check_roundtrip(ids, p3_dir / "roundtrip.pt")  # overwrites the weights: throwaway adapter
    checks[name] = ad.param_table()
    del ad
    torch.cuda.empty_cache()

params = checks["mixlora-none"]
RUNS = {
    "mixlora-none": lambda m: Adapter.mixlora(m, p3, "none"),
    "mixlora-aux": lambda m: Adapter.mixlora(m, p3, "aux"),
    "mixlora-bias": lambda m: Adapter.mixlora(m, p3, "bias"),
    f"lora-r{p3['lora_rank']}": lambda m: Adapter.lora(m, p3["lora_rank"]),
    f"lora-r{params['lora_rank_matched_trainable']}": lambda m: Adapter.lora(m, params["lora_rank_matched_trainable"]),
    f"lora-r{params['lora_rank_matched_active']}": lambda m: Adapter.lora(m, params["lora_rank_matched_active"]),
}
pd.DataFrame(checks).T

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

trainable 117,555,200 == expected, active per token 32,915,456
identity: max|diff| = 1.85e-04
save/load round-trip: exact

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

trainable 117,555,200 == expected, active per token 32,915,456
identity: max|diff| = 1.64e-04
save/load round-trip: exact

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

trainable 18,464,768 == expected, active per token 18,464,768
identity: max|diff| = 0.00e+00
save/load round-trip: exact

,trainable,active,lora_rank_matched_trainable,lora_rank_matched_active
mixlora-none,117555200,32915456,102,29
mixlora-bias,117555200,32915456,102,29
lora,18464768,18464768,16,16

In [8]:
for name in ["mixlora-none", f"lora-r{params['lora_rank_matched_trainable']}"]:
    trainer = SFTTrainer(RUNS[name](load_base()), data, p3, seed=cfg["seed"])
    print(name, trainer.train(out_dir(cfg, "part3", "timing", name), max_steps=8))
    del trainer
    torch.cuda.empty_cache()

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2625, "aux_per_layer": 1.268, "grad_norm": 1.198, "step": 1, "lr": 2e-05, "sec_per_step": 5.835, "max_mem_gb": 7.018, "maxvio_mean": 1.39}
{"loss": 0.475, "aux_per_layer": 1.256, "grad_norm": 0.8622, "step": 8, "lr": 9e-05, "sec_per_step": 4.243, "max_mem_gb": 7.485, "maxvio_mean": 1.353}
mixlora-none {'steps': 8, 'sec_per_step': 4.100810209910075, 'peak_mem_gb': 7.484743118286133}

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2625, "aux_per_layer": 0.0, "grad_norm": 3.568, "step": 1, "lr": 2e-05, "sec_per_step": 2.524, "max_mem_gb": 5.176}
{"loss": 0.4419, "aux_per_layer": 0.0, "grad_norm": 1.84, "step": 8, "lr": 9e-05, "sec_per_step": 2.177, "max_mem_gb": 5.494}
lora-r102 {'steps': 8, 'sec_per_step': 2.2386882305145264, 'peak_mem_gb': 5.494174480438232}

In [9]:
start_run("base", "eval")
trainer = SFTTrainer(Adapter.lora(load_base(), p3["lora_rank"]), data, p3, seed=cfg["seed"])
base_metrics = trainer.evaluate(out_dir(cfg, "part3", "base"), {"trainable": 0, "active": 0})
wl.finish()
del trainer
torch.cuda.empty_cache()

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: pavlokhomenko2307 (ai340-nlp) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_150030-iqc3hqpo
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run base
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/iqc3hqpo

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

wandb: updating run metadata

{'val_loss': 0.4033941819560515, 'chrf': 55.45697659952204, 'exact_match': 0.0033333333333333335, 'trainable': 0, 'active': 0}

wandb:
wandb: Run summary:
wandb:      active 0
wandb:        chrf 55.45698
wandb: exact_match 0.00333
wandb:   trainable 0
wandb:    val_loss 0.40339
wandb:
wandb: 🚀 View run base at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/iqc3hqpo
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_150030-iqc3hqpo/logs

In [10]:
for name, make in RUNS.items():
    run_dir = out_dir(cfg, "part3", name)
    if (run_dir / "metrics.json").exists():
        continue
    start_run(name, "train", run=name)
    trainer = SFTTrainer(make(load_base()), data, p3, seed=cfg["seed"])
    timing = trainer.train(run_dir)
    trainer.adapter.save(run_dir / "adapter.pt")
    trainer.evaluate(run_dir, timing)
    wl.finish()
    del trainer
    torch.cuda.empty_cache()

wandb: setting up run zvj9615p
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_150446-zvj9615p
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mixlora-none
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/zvj9615p

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2626, "aux_per_layer": 1.22, "grad_norm": 1.208, "step": 1, "lr": 2e-05, "sec_per_step": 4.96, "max_mem_gb": 7.002, "maxvio_mean": 1.218}
{"loss": 0.3451, "aux_per_layer": 1.211, "grad_norm": 0.7347, "step": 11, "lr": 0.00012, "sec_per_step": 4.137, "max_mem_gb": 7.482, "maxvio_mean": 1.219}
{"loss": 0.2519, "aux_per_layer": 1.211, "grad_norm": 0.4439, "step": 21, "lr": 0.0002, "sec_per_step": 4.212, "max_mem_gb": 7.61, "maxvio_mean": 1.142}
{"loss": 0.2595, "aux_per_layer": 1.239, "grad_norm": 0.4329, "step": 31, "lr": 0.000199, "sec_per_step": 4.689, "max_mem_gb": 7.61, "maxvio_mean": 1.298}
{"loss": 0.3324, "aux_per_layer": 1.248, "grad_norm": 0.4711, "step": 41, "lr": 0.0001963, "sec_per_step": 4.273, "max_mem_gb": 7.61, "maxvio_mean": 1.287}
{"loss": 0.3506, "aux_per_layer": 1.288, "grad_norm": 0.7066, "step": 51, "lr": 0.0001921, "sec_per_step": 4.755, "max_mem_gb": 7.61, "maxvio_mean": 1.432}
{"loss": 0.3664, "aux_per_layer": 1.329, "grad_norm": 0.5129, "step": 61, "lr": 0.0001863, "sec_per_step": 4.826, "max_mem_gb": 7.61, "maxvio_mean": 1.513}
{"loss": 0.258, "aux_per_layer": 1.349, "grad_norm": 0.4086, "step": 71, "lr": 0.000179, "sec_per_step": 3.999, "max_mem_gb": 7.61, "maxvio_mean": 1.567}
{"loss": 0.2285, "aux_per_layer": 1.361, "grad_norm": 0.5129, "step": 81, "lr": 0.0001705, "sec_per_step": 4.321, "max_mem_gb": 7.61, "maxvio_mean": 1.594}
{"loss": 0.2312, "aux_per_layer": 1.372, "grad_norm": 0.5772, "step": 91, "lr": 0.0001609, "sec_per_step": 4.4, "max_mem_gb": 7.61, "maxvio_mean": 1.622}
{"loss": 0.07516, "aux_per_layer": 1.389, "grad_norm": 0.2014, "step": 101, "lr": 0.0001503, "sec_per_step": 4.746, "max_mem_gb": 7.61, "maxvio_mean": 1.645}
{"loss": 0.2084, "aux_per_layer": 1.395, "grad_norm": 0.3289, "step": 111, "lr": 0.000139, "sec_per_step": 4.733, "max_mem_gb": 7.61, "maxvio_mean": 1.658}
{"loss": 0.1722, "aux_per_layer": 1.408, "grad_norm": 0.3625, "step": 121, "lr": 0.0001271, "sec_per_step": 4.579, "max_mem_gb": 7.61, "maxvio_mean": 1.718}
{"loss": 0.2487, "aux_per_layer": 1.431, "grad_norm": 0.3751, "step": 131, "lr": 0.0001149, "sec_per_step": 4.469, "max_mem_gb": 7.61, "maxvio_mean": 1.762}
{"loss": 0.1713, "aux_per_layer": 1.423, "grad_norm": 0.5577, "step": 141, "lr": 0.0001026, "sec_per_step": 4.939, "max_mem_gb": 7.615, "maxvio_mean": 1.722}
{"loss": 0.3123, "aux_per_layer": 1.44, "grad_norm": 0.4359, "step": 151, "lr": 9.049e-05, "sec_per_step": 4.649, "max_mem_gb": 7.615, "maxvio_mean": 1.747}
{"loss": 0.2099, "aux_per_layer": 1.446, "grad_norm": 0.3876, "step": 161, "lr": 7.871e-05, "sec_per_step": 4.908, "max_mem_gb": 7.639, "maxvio_mean": 1.755}
{"loss": 0.1857, "aux_per_layer": 1.434, "grad_norm": 0.3673, "step": 171, "lr": 6.751e-05, "sec_per_step": 4.717, "max_mem_gb": 7.639, "maxvio_mean": 1.732}
{"loss": 0.3849, "aux_per_layer": 1.447, "grad_norm": 0.5808, "step": 181, "lr": 5.71e-05, "sec_per_step": 4.482, "max_mem_gb": 7.643, "maxvio_mean": 1.767}
{"loss": 0.1094, "aux_per_layer": 1.411, "grad_norm": 0.3656, "step": 191, "lr": 4.768e-05, "sec_per_step": 4.619, "max_mem_gb": 7.644, "maxvio_mean": 1.706}
{"loss": 0.1269, "aux_per_layer": 1.431, "grad_norm": 0.3241, "step": 201, "lr": 3.942e-05, "sec_per_step": 4.506, "max_mem_gb": 7.644, "maxvio_mean": 1.75}
{"loss": 0.1855, "aux_per_layer": 1.432, "grad_norm": 0.3414, "step": 211, "lr": 3.247e-05, "sec_per_step": 4.044, "max_mem_gb": 7.644, "maxvio_mean": 1.756}
{"loss": 0.1265, "aux_per_layer": 1.429, "grad_norm": 0.2577, "step": 221, "lr": 2.697e-05, "sec_per_step": 4.053, "max_mem_gb": 7.644, "maxvio_mean": 1.762}
{"loss": 0.265, "aux_per_layer": 1.419, "grad_norm": 0.4792, "step": 231, "lr": 2.301e-05, "sec_per_step": 5.333, "max_mem_gb": 7.644, "maxvio_mean": 1.72}
{"loss": 0.1919, "aux_per_layer": 1.431, "grad_norm": 0.4022, "step": 241, "lr": 2.068e-05, "sec_per_step": 4.09, "max_mem_gb": 7.644, "maxvio_mean": 1.727}
{"loss": 0.2303, "aux_per_layer": 1.433, "grad_norm": 0.5009, "step": 250, "lr": 2e-05, "sec_per_step": 4.727, "max_mem_gb": 7.644, "maxvio_mean": 1.743}

wandb: updating run metadata

{'val_loss': 0.17527449178992285, 'chrf': 92.99179173286699, 'exact_match': 0.42, 'trainable': 117555200, 'active': 32915456, 'steps': 250, 'sec_per_step': 4.374765920639038, 'peak_mem_gb': 7.643589496612549}

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml
wandb:
wandb: Run history:
wandb:   train/aux_per_layer ▁▁▂▂▂▂▃▃▃▄▅▄▅▅▆▆▆▆▆▆▇▇██▇██▇█▇▇█▇▇▇█▇█▇█
wandb:       train/grad_norm ▄▄█▂▂▂▂▂▂▃▂▂▂▁▂▂▂▂▂▁▂▁▁▂▂▂▁▂▂▂▂▁▁▁▂▂▁▂▂▂
wandb:            train/loss ▄█▄▄▃▄▄▅▁▂▃▂▃▄▂▃▂▂▃▁▂▃▂▃▃▁▂▂▂▃▃▃▃▃▂▂▂▃▁▃
wandb:              train/lr ▁▃▅▆▆██████████▇▇▇▆▆▅▅▅▄▄▃▃▃▃▃▂▂▂▂▂▁▁▁▁▁
wandb:      train/max_mem_gb ▁▁▁▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇███████████████████
wandb: train/maxvio/layer_00 ▁▁▁▁▁▂▄▄▃▅▇▇▇▇▇█▇█▇▇▇▆▇▆▇▇▆▆▇█▇▆▆▆▆▆▇▇▆▆
wandb: train/maxvio/layer_01 ▄▄▄▂▂▁▃▁▂▃▅▇▆▇▇▇▇▅▇▆█▆▆▄▄▅▂▃▂▆▇▇▆▆▆▅▇▅▆▅
wandb: train/maxvio/layer_02 █▇▇▆▄▂▂▂▁▁▄▅▆▆▇▆▇▅▅▅█▇▇▆▇▆▆▆▆▆▆▆▆▅▅▆▇▆▇▇
wandb: train/maxvio/layer_03 ▁▁▁▂▃▂▂▂▂▂▃▄▃▃▃▂▃▃▆▆▇██▇▇▇▇▇▇▇▇▇▇▆▇▆▆▆▇▆
wandb: train/maxvio/layer_04 ▄▅▅█▇▇▆▅▄▅▃▂▃▁▃▄▄▄▅▄▃▃▅▇▇▇▆▇▇▇▇▇▇██▇▇▇██
wandb:                   +53 ...
wandb:
wandb: Run summary:
wandb:              active 32915456
wandb:                chrf 92.99179
wandb:         exact_match 0.42
wandb:         peak_mem_gb 7.64359
wandb:        sec_per_step 4.37477
wandb:               steps 250
wandb: train/aux_per_layer 1.43294
wandb:     train/grad_norm 0.50094
wandb:          train/loss 0.23027
wandb:            train/lr 2e-05
wandb:                 +61 ...
wandb:
wandb: 🚀 View run mixlora-none at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/zvj9615p
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_150446-zvj9615p/logs
wandb: setting up run 68wjdvh3
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_152921-68wjdvh3
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mixlora-aux
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/68wjdvh3

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2627, "aux_per_layer": 1.217, "grad_norm": 1.253, "step": 1, "lr": 2e-05, "sec_per_step": 4.697, "max_mem_gb": 7.001, "maxvio_mean": 1.179}
{"loss": 0.3442, "aux_per_layer": 1.088, "grad_norm": 0.7379, "step": 11, "lr": 0.00012, "sec_per_step": 4.09, "max_mem_gb": 7.486, "maxvio_mean": 0.6786}
{"loss": 0.2495, "aux_per_layer": 1.036, "grad_norm": 0.4538, "step": 21, "lr": 0.0002, "sec_per_step": 4.236, "max_mem_gb": 7.612, "maxvio_mean": 0.3958}
{"loss": 0.2554, "aux_per_layer": 1.017, "grad_norm": 0.4655, "step": 31, "lr": 0.000199, "sec_per_step": 4.679, "max_mem_gb": 7.612, "maxvio_mean": 0.2804}
{"loss": 0.3292, "aux_per_layer": 1.008, "grad_norm": 0.5003, "step": 41, "lr": 0.0001963, "sec_per_step": 4.244, "max_mem_gb": 7.612, "maxvio_mean": 0.212}
{"loss": 0.3522, "aux_per_layer": 1.009, "grad_norm": 0.6991, "step": 51, "lr": 0.0001921, "sec_per_step": 4.661, "max_mem_gb": 7.612, "maxvio_mean": 0.2201}
{"loss": 0.366, "aux_per_layer": 1.009, "grad_norm": 0.5451, "step": 61, "lr": 0.0001863, "sec_per_step": 4.821, "max_mem_gb": 7.612, "maxvio_mean": 0.2171}
{"loss": 0.2544, "aux_per_layer": 1.005, "grad_norm": 0.4162, "step": 71, "lr": 0.000179, "sec_per_step": 3.959, "max_mem_gb": 7.612, "maxvio_mean": 0.164}
{"loss": 0.2234, "aux_per_layer": 1.007, "grad_norm": 0.509, "step": 81, "lr": 0.0001705, "sec_per_step": 4.212, "max_mem_gb": 7.612, "maxvio_mean": 0.1737}
{"loss": 0.2315, "aux_per_layer": 1.006, "grad_norm": 0.5279, "step": 91, "lr": 0.0001609, "sec_per_step": 4.269, "max_mem_gb": 7.612, "maxvio_mean": 0.1999}
{"loss": 0.07688, "aux_per_layer": 1.005, "grad_norm": 0.2118, "step": 101, "lr": 0.0001503, "sec_per_step": 4.641, "max_mem_gb": 7.612, "maxvio_mean": 0.1735}
{"loss": 0.2003, "aux_per_layer": 1.004, "grad_norm": 0.3288, "step": 111, "lr": 0.000139, "sec_per_step": 4.594, "max_mem_gb": 7.612, "maxvio_mean": 0.1611}
{"loss": 0.1708, "aux_per_layer": 1.007, "grad_norm": 0.355, "step": 121, "lr": 0.0001271, "sec_per_step": 4.119, "max_mem_gb": 7.612, "maxvio_mean": 0.1915}
{"loss": 0.2416, "aux_per_layer": 1.005, "grad_norm": 0.3914, "step": 131, "lr": 0.0001149, "sec_per_step": 4.28, "max_mem_gb": 7.612, "maxvio_mean": 0.1412}
{"loss": 0.1627, "aux_per_layer": 1.005, "grad_norm": 0.5096, "step": 141, "lr": 0.0001026, "sec_per_step": 4.5, "max_mem_gb": 7.612, "maxvio_mean": 0.1428}
{"loss": 0.3074, "aux_per_layer": 1.005, "grad_norm": 0.4574, "step": 151, "lr": 9.049e-05, "sec_per_step": 4.478, "max_mem_gb": 7.612, "maxvio_mean": 0.1488}
{"loss": 0.2081, "aux_per_layer": 1.005, "grad_norm": 0.4166, "step": 161, "lr": 7.871e-05, "sec_per_step": 4.8, "max_mem_gb": 7.612, "maxvio_mean": 0.1684}
{"loss": 0.1806, "aux_per_layer": 1.004, "grad_norm": 0.3456, "step": 171, "lr": 6.751e-05, "sec_per_step": 4.542, "max_mem_gb": 7.612, "maxvio_mean": 0.1542}
{"loss": 0.3967, "aux_per_layer": 1.003, "grad_norm": 0.5864, "step": 181, "lr": 5.71e-05, "sec_per_step": 4.332, "max_mem_gb": 7.612, "maxvio_mean": 0.1426}
{"loss": 0.09986, "aux_per_layer": 1.004, "grad_norm": 0.3454, "step": 191, "lr": 4.768e-05, "sec_per_step": 4.57, "max_mem_gb": 7.616, "maxvio_mean": 0.1368}
{"loss": 0.1249, "aux_per_layer": 1.003, "grad_norm": 0.3315, "step": 201, "lr": 3.942e-05, "sec_per_step": 4.461, "max_mem_gb": 7.616, "maxvio_mean": 0.1283}
{"loss": 0.186, "aux_per_layer": 1.003, "grad_norm": 0.3591, "step": 211, "lr": 3.247e-05, "sec_per_step": 3.947, "max_mem_gb": 7.616, "maxvio_mean": 0.1127}
{"loss": 0.1254, "aux_per_layer": 1.003, "grad_norm": 0.2569, "step": 221, "lr": 2.697e-05, "sec_per_step": 3.913, "max_mem_gb": 7.616, "maxvio_mean": 0.1386}
{"loss": 0.2612, "aux_per_layer": 1.004, "grad_norm": 0.4641, "step": 231, "lr": 2.301e-05, "sec_per_step": 5.249, "max_mem_gb": 7.616, "maxvio_mean": 0.1346}
{"loss": 0.1895, "aux_per_layer": 1.002, "grad_norm": 0.4442, "step": 241, "lr": 2.068e-05, "sec_per_step": 3.964, "max_mem_gb": 7.616, "maxvio_mean": 0.1031}
{"loss": 0.2271, "aux_per_layer": 1.002, "grad_norm": 0.5045, "step": 250, "lr": 2e-05, "sec_per_step": 4.645, "max_mem_gb": 7.616, "maxvio_mean": 0.1213}

wandb: updating run metadata

{'val_loss': 0.1746782019510838, 'chrf': 92.55174925901734, 'exact_match': 0.41333333333333333, 'trainable': 117555200, 'active': 32915456, 'steps': 250, 'sec_per_step': 4.288287236739178, 'peak_mem_gb': 7.616357803344727}

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml
wandb:
wandb: Run history:
wandb:   train/aux_per_layer ██▇▆▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:       train/grad_norm █▇▅▄▂▂▃▃▂▃▂▁▁▃▂▂▃▂▂▃▃▁▃▂▂▃▃▂▂▂▃▂▃▂▁▂▃▃▂▂
wandb:            train/loss ▄██▄▅▂▃▄▆▄▃▅▆▄▂▃▄▂▂▅▂▄▃▄▄▄▂▃▄▄▄▁▃▂▅▃▂▂▁▃
wandb:              train/lr ▃▄██████▇▇▇▇▇▇▇▆▆▆▆▅▅▅▅▄▄▄▄▄▃▃▂▂▂▂▁▁▁▁▁▁
wandb:      train/max_mem_gb ▁▁▁▁▄███████████████████████████████████
wandb: train/maxvio/layer_00 █▇▄▃▂▂▂▃▂▂▂▃▂▂▂▃▁▂▃▂▄▂▃▂▃▃▂▃▂▂▂▂▂▂▁▁▁▂▁▂
wandb: train/maxvio/layer_01 █▇▆▄▃▂▂▂▂▂▂▃▂▂▂▂▂▁▁▁▁▁▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁▂▁▁
wandb: train/maxvio/layer_02 ██▄▃▃▃▃▄▄▁▂▂▂▁▁▂▂▁▂▁▂▁▁▂▁▁▂▁▁▂▂▁▁▁▂▂▁▁▁▂
wandb: train/maxvio/layer_03 ██▄▄▃▂▂▂▁▂▁▁▁▂▁▁▁▂▁▁▁▁▂▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▂▁
wandb: train/maxvio/layer_04 █▇█▇▃▃▃▅▄▄▃▁▂▂▁▃▂▂▂▂▁▂▂▁▂▁▂▁▂▁▂▂▂▁▁▁▂▂▂▂
wandb:                   +53 ...
wandb:
wandb: Run summary:
wandb:              active 32915456
wandb:                chrf 92.55175
wandb:         exact_match 0.41333
wandb:         peak_mem_gb 7.61636
wandb:        sec_per_step 4.28829
wandb:               steps 250
wandb: train/aux_per_layer 1.00238
wandb:     train/grad_norm 0.50445
wandb:          train/loss 0.22714
wandb:            train/lr 2e-05
wandb:                 +61 ...
wandb:
wandb: 🚀 View run mixlora-aux at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/68wjdvh3
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_152921-68wjdvh3/logs
wandb: setting up run 5jjxuvsu
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_155411-5jjxuvsu
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mixlora-bias
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/5jjxuvsu

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2627, "aux_per_layer": 1.217, "grad_norm": 1.218, "step": 1, "lr": 2e-05, "sec_per_step": 5.082, "max_mem_gb": 7.001, "maxvio_mean": 1.179}
{"loss": 0.3445, "aux_per_layer": 1.19, "grad_norm": 0.7208, "step": 11, "lr": 0.00012, "sec_per_step": 4.104, "max_mem_gb": 7.487, "maxvio_mean": 1.121}
{"loss": 0.2533, "aux_per_layer": 1.208, "grad_norm": 0.4503, "step": 21, "lr": 0.0002, "sec_per_step": 4.249, "max_mem_gb": 7.613, "maxvio_mean": 1.152}
{"loss": 0.2604, "aux_per_layer": 1.198, "grad_norm": 0.4274, "step": 31, "lr": 0.000199, "sec_per_step": 4.677, "max_mem_gb": 7.613, "maxvio_mean": 1.133}
{"loss": 0.3299, "aux_per_layer": 1.219, "grad_norm": 0.4766, "step": 41, "lr": 0.0001963, "sec_per_step": 4.262, "max_mem_gb": 7.613, "maxvio_mean": 1.181}
{"loss": 0.3519, "aux_per_layer": 1.262, "grad_norm": 0.7111, "step": 51, "lr": 0.0001921, "sec_per_step": 4.725, "max_mem_gb": 7.613, "maxvio_mean": 1.357}
{"loss": 0.3696, "aux_per_layer": 1.265, "grad_norm": 0.5321, "step": 61, "lr": 0.0001863, "sec_per_step": 4.489, "max_mem_gb": 7.613, "maxvio_mean": 1.238}
{"loss": 0.2509, "aux_per_layer": 1.266, "grad_norm": 0.4134, "step": 71, "lr": 0.000179, "sec_per_step": 3.976, "max_mem_gb": 7.613, "maxvio_mean": 1.152}
{"loss": 0.224, "aux_per_layer": 1.281, "grad_norm": 0.5492, "step": 81, "lr": 0.0001705, "sec_per_step": 4.627, "max_mem_gb": 7.613, "maxvio_mean": 1.206}
{"loss": 0.2305, "aux_per_layer": 1.294, "grad_norm": 0.5213, "step": 91, "lr": 0.0001609, "sec_per_step": 3.978, "max_mem_gb": 7.613, "maxvio_mean": 1.251}
{"loss": 0.07936, "aux_per_layer": 1.324, "grad_norm": 0.1945, "step": 101, "lr": 0.0001503, "sec_per_step": 4.693, "max_mem_gb": 7.613, "maxvio_mean": 1.355}
{"loss": 0.2021, "aux_per_layer": 1.332, "grad_norm": 0.3161, "step": 111, "lr": 0.000139, "sec_per_step": 4.728, "max_mem_gb": 7.613, "maxvio_mean": 1.343}
{"loss": 0.165, "aux_per_layer": 1.332, "grad_norm": 0.3395, "step": 121, "lr": 0.0001271, "sec_per_step": 4.234, "max_mem_gb": 7.613, "maxvio_mean": 1.293}
{"loss": 0.2405, "aux_per_layer": 1.346, "grad_norm": 0.3674, "step": 131, "lr": 0.0001149, "sec_per_step": 4.378, "max_mem_gb": 7.613, "maxvio_mean": 1.312}
{"loss": 0.1642, "aux_per_layer": 1.314, "grad_norm": 0.4298, "step": 141, "lr": 0.0001026, "sec_per_step": 4.929, "max_mem_gb": 7.613, "maxvio_mean": 1.218}
{"loss": 0.3083, "aux_per_layer": 1.326, "grad_norm": 0.4326, "step": 151, "lr": 9.049e-05, "sec_per_step": 4.551, "max_mem_gb": 7.613, "maxvio_mean": 1.232}
{"loss": 0.2141, "aux_per_layer": 1.328, "grad_norm": 0.3855, "step": 161, "lr": 7.871e-05, "sec_per_step": 4.88, "max_mem_gb": 7.613, "maxvio_mean": 1.184}
{"loss": 0.1817, "aux_per_layer": 1.307, "grad_norm": 0.3205, "step": 171, "lr": 6.751e-05, "sec_per_step": 4.673, "max_mem_gb": 7.613, "maxvio_mean": 1.119}
{"loss": 0.3859, "aux_per_layer": 1.312, "grad_norm": 0.5717, "step": 181, "lr": 5.71e-05, "sec_per_step": 4.396, "max_mem_gb": 7.613, "maxvio_mean": 1.137}
{"loss": 0.1071, "aux_per_layer": 1.268, "grad_norm": 0.3648, "step": 191, "lr": 4.768e-05, "sec_per_step": 4.552, "max_mem_gb": 7.613, "maxvio_mean": 1.027}
{"loss": 0.1266, "aux_per_layer": 1.29, "grad_norm": 0.3364, "step": 201, "lr": 3.942e-05, "sec_per_step": 4.414, "max_mem_gb": 7.613, "maxvio_mean": 1.066}
{"loss": 0.1865, "aux_per_layer": 1.288, "grad_norm": 0.3574, "step": 211, "lr": 3.247e-05, "sec_per_step": 3.966, "max_mem_gb": 7.613, "maxvio_mean": 1.052}
{"loss": 0.1246, "aux_per_layer": 1.278, "grad_norm": 0.2574, "step": 221, "lr": 2.697e-05, "sec_per_step": 3.964, "max_mem_gb": 7.613, "maxvio_mean": 1.003}
{"loss": 0.2656, "aux_per_layer": 1.268, "grad_norm": 0.4488, "step": 231, "lr": 2.301e-05, "sec_per_step": 4.928, "max_mem_gb": 7.613, "maxvio_mean": 0.9797}
{"loss": 0.1936, "aux_per_layer": 1.274, "grad_norm": 0.4389, "step": 241, "lr": 2.068e-05, "sec_per_step": 4.026, "max_mem_gb": 7.613, "maxvio_mean": 0.9878}
{"loss": 0.232, "aux_per_layer": 1.273, "grad_norm": 0.472, "step": 250, "lr": 2e-05, "sec_per_step": 4.687, "max_mem_gb": 7.613, "maxvio_mean": 0.9783}

wandb: updating run metadata

{'val_loss': 0.17527491454017324, 'chrf': 92.82805770358277, 'exact_match': 0.43, 'trainable': 117555200, 'active': 32915456, 'steps': 250, 'sec_per_step': 4.330522079857028, 'peak_mem_gb': 7.613243103027344}

wandb:
wandb: Run history:
wandb:   train/aux_per_layer ▂▂▁▁▁▂▂▂▂▄▄▅▅▄▅▅▅██▇▇▇██▇█▇▇▇▇█▆▅▇▅▅▅▅▃▅
wandb:       train/grad_norm ██▃▃▂▂▇▃▃▃▃▂▁▄▅▂▄▁▃▃▃▁▂▄▂▃▂▃▃▃▃▃▃▃▂▂▂▂▃▃
wandb:            train/loss ▇▆▆▅▅▂▂▄▄▂▅▃▄▂█▄▄▂▄▂▃▄▃▁▃▄▄▂▄▃▄▄▃▄▃▂▄▂▃▃
wandb:              train/lr ▃▄▄▇███████▇▇▇▇▇▇▇▇▇▆▆▅▅▅▅▅▄▄▄▄▃▂▂▂▂▁▁▁▁
wandb:      train/max_mem_gb ▁▁▄▄████████████████████████████████████
wandb: train/maxvio/layer_00 ▂▂▂▂▃▅▆▇▇█▆▅▇▅▅▇▇▇▇▇▆▅▅▄▄▃▄▄▃▃▄▂▂▁▂▁▂▂▁▂
wandb: train/maxvio/layer_01 ▂▁▁▂▂▂▂▂▂▃▂▃▄▅▅▆▇▇▇▇▇▇▇▇█▇▇█▇▇▇▆▆▇▆▇▆▇▆▆
wandb: train/maxvio/layer_02 ▃▂▃▂▂▂▂▂▃▂▁▂▂▁▂▆██▇▅▄▃▃▃▃▂▃▂▂▂▂▂▂▂▃▂▃▂▂▂
wandb: train/maxvio/layer_03 ▇▆▄▄▃▂▂▁▂▁▃▄▄▅▆█▆▆▆▆█▇▆▇▇▇▇▇▆▆▅▆▅▅▅▄▃▅▃▄
wandb: train/maxvio/layer_04 ▁▁▁▄▆█▇█▅▅▅▅▄▃▄▅▅▄▄▅▄▄▅▅▄▄▃▅▄▄▄▃▅▄▃▃▄▃▃▃
wandb:                   +53 ...
wandb:
wandb: Run summary:
wandb:              active 32915456
wandb:                chrf 92.82806
wandb:         exact_match 0.43
wandb:         peak_mem_gb 7.61324
wandb:        sec_per_step 4.33052
wandb:               steps 250
wandb: train/aux_per_layer 1.27288
wandb:     train/grad_norm 0.47197
wandb:          train/loss 0.23203
wandb:            train/lr 2e-05
wandb:                 +61 ...
wandb:
wandb: 🚀 View run mixlora-bias at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/5jjxuvsu
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_155411-5jjxuvsu/logs
wandb: setting up run tpilqhga
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_161858-tpilqhga
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r16
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/tpilqhga

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2625, "aux_per_layer": 0.0, "grad_norm": 1.383, "step": 1, "lr": 2e-05, "sec_per_step": 2.905, "max_mem_gb": 3.747}
{"loss": 0.3499, "aux_per_layer": 0.0, "grad_norm": 0.8486, "step": 11, "lr": 0.00012, "sec_per_step": 2.249, "max_mem_gb": 3.985}
{"loss": 0.252, "aux_per_layer": 0.0, "grad_norm": 0.4788, "step": 21, "lr": 0.0002, "sec_per_step": 2.341, "max_mem_gb": 4.087}
{"loss": 0.2632, "aux_per_layer": 0.0, "grad_norm": 0.5032, "step": 31, "lr": 0.000199, "sec_per_step": 2.491, "max_mem_gb": 4.222}
{"loss": 0.3213, "aux_per_layer": 0.0, "grad_norm": 0.4939, "step": 41, "lr": 0.0001963, "sec_per_step": 2.343, "max_mem_gb": 4.222}
{"loss": 0.3515, "aux_per_layer": 0.0, "grad_norm": 0.7563, "step": 51, "lr": 0.0001921, "sec_per_step": 2.742, "max_mem_gb": 4.222}
{"loss": 0.3594, "aux_per_layer": 0.0, "grad_norm": 0.5587, "step": 61, "lr": 0.0001863, "sec_per_step": 2.572, "max_mem_gb": 4.222}
{"loss": 0.254, "aux_per_layer": 0.0, "grad_norm": 0.4563, "step": 71, "lr": 0.000179, "sec_per_step": 2.195, "max_mem_gb": 4.222}
{"loss": 0.2255, "aux_per_layer": 0.0, "grad_norm": 0.5316, "step": 81, "lr": 0.0001705, "sec_per_step": 2.45, "max_mem_gb": 4.342}
{"loss": 0.2306, "aux_per_layer": 0.0, "grad_norm": 0.5735, "step": 91, "lr": 0.0001609, "sec_per_step": 2.2, "max_mem_gb": 4.342}
{"loss": 0.08103, "aux_per_layer": 0.0, "grad_norm": 0.229, "step": 101, "lr": 0.0001503, "sec_per_step": 2.742, "max_mem_gb": 4.342}
{"loss": 0.208, "aux_per_layer": 0.0, "grad_norm": 0.3564, "step": 111, "lr": 0.000139, "sec_per_step": 2.709, "max_mem_gb": 4.342}
{"loss": 0.1675, "aux_per_layer": 0.0, "grad_norm": 0.3965, "step": 121, "lr": 0.0001271, "sec_per_step": 2.367, "max_mem_gb": 4.342}
{"loss": 0.2475, "aux_per_layer": 0.0, "grad_norm": 0.4164, "step": 131, "lr": 0.0001149, "sec_per_step": 2.482, "max_mem_gb": 4.342}
{"loss": 0.1715, "aux_per_layer": 0.0, "grad_norm": 0.545, "step": 141, "lr": 0.0001026, "sec_per_step": 2.626, "max_mem_gb": 4.342}
{"loss": 0.3109, "aux_per_layer": 0.0, "grad_norm": 0.4868, "step": 151, "lr": 9.049e-05, "sec_per_step": 2.613, "max_mem_gb": 4.342}
{"loss": 0.2169, "aux_per_layer": 0.0, "grad_norm": 0.4235, "step": 161, "lr": 7.871e-05, "sec_per_step": 2.852, "max_mem_gb": 4.342}
{"loss": 0.18, "aux_per_layer": 0.0, "grad_norm": 0.3699, "step": 171, "lr": 6.751e-05, "sec_per_step": 2.339, "max_mem_gb": 4.342}
{"loss": 0.3815, "aux_per_layer": 0.0, "grad_norm": 0.6093, "step": 181, "lr": 5.71e-05, "sec_per_step": 2.49, "max_mem_gb": 4.342}
{"loss": 0.1092, "aux_per_layer": 0.0, "grad_norm": 0.3975, "step": 191, "lr": 4.768e-05, "sec_per_step": 2.609, "max_mem_gb": 4.342}
{"loss": 0.1306, "aux_per_layer": 0.0, "grad_norm": 0.3968, "step": 201, "lr": 3.942e-05, "sec_per_step": 2.261, "max_mem_gb": 4.342}
{"loss": 0.1876, "aux_per_layer": 0.0, "grad_norm": 0.3975, "step": 211, "lr": 3.247e-05, "sec_per_step": 2.194, "max_mem_gb": 4.342}
{"loss": 0.1268, "aux_per_layer": 0.0, "grad_norm": 0.2972, "step": 221, "lr": 2.697e-05, "sec_per_step": 2.172, "max_mem_gb": 4.342}
{"loss": 0.2686, "aux_per_layer": 0.0, "grad_norm": 0.4974, "step": 231, "lr": 2.301e-05, "sec_per_step": 2.895, "max_mem_gb": 4.342}
{"loss": 0.1908, "aux_per_layer": 0.0, "grad_norm": 0.4894, "step": 241, "lr": 2.068e-05, "sec_per_step": 2.157, "max_mem_gb": 4.342}
{"loss": 0.2294, "aux_per_layer": 0.0, "grad_norm": 0.5758, "step": 250, "lr": 2e-05, "sec_per_step": 2.72, "max_mem_gb": 4.342}

wandb: updating run metadata

{'val_loss': 0.17733292469732323, 'chrf': 92.66919199881497, 'exact_match': 0.41333333333333333, 'trainable': 18464768, 'active': 18464768, 'steps': 250, 'sec_per_step': 2.3620301898644893, 'peak_mem_gb': 4.341932773590088}

wandb: uploading history steps 249-249, summary, console lines 26-26
wandb:
wandb: Run history:
wandb: train/aux_per_layer ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     train/grad_norm █▆▃▁▂▂▂▃▂▅▃▂▂▂▃▃▁▂▂▃▄▂▂▁▃▂▃▂▂▃▄▂▂▁▂▂▁▂▄▂
wandb:          train/loss ▆▆▅▂▅▆▂▂▄▃▄▂▃▂█▃▄▄▄▄▅▁▄▃▃▃▃▃▄▃▂▇▅▃▁▃▄▆▂▃
wandb:            train/lr ▂▃▃███████▇▇▇▇▇▅▅▅▅▄▄▄▄▃▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁
wandb:    train/max_mem_gb ▁▁▁▁▁▁██████████████████████████████████
wandb:  train/sec_per_step ▆▆▄▅▆▅▄▅▄▄▁▆▃▆▄▇▃▅▆▆▆▄█▄▇▆▅▆█▇▃▅▃▄▄▄▆▇▅▅
wandb:
wandb: Run summary:
wandb:              active 18464768
wandb:                chrf 92.66919
wandb:         exact_match 0.41333
wandb:         peak_mem_gb 4.34193
wandb:        sec_per_step 2.36203
wandb:               steps 250
wandb: train/aux_per_layer 0
wandb:     train/grad_norm 0.57575
wandb:          train/loss 0.22942
wandb:            train/lr 2e-05
wandb:                  +4 ...
wandb:
wandb: 🚀 View run lora-r16 at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/tpilqhga
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_161858-tpilqhga/logs
wandb: setting up run bl0n1jjl
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_163124-bl0n1jjl
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r102
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/bl0n1jjl

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2625, "aux_per_layer": 0.0, "grad_norm": 3.568, "step": 1, "lr": 2e-05, "sec_per_step": 2.862, "max_mem_gb": 5.176}
{"loss": 0.2758, "aux_per_layer": 0.0, "grad_norm": 1.222, "step": 11, "lr": 0.00012, "sec_per_step": 2.522, "max_mem_gb": 5.494}
{"loss": 0.2656, "aux_per_layer": 0.0, "grad_norm": 1.041, "step": 21, "lr": 0.0002, "sec_per_step": 2.571, "max_mem_gb": 5.574}
{"loss": 0.2759, "aux_per_layer": 0.0, "grad_norm": 0.8439, "step": 31, "lr": 0.000199, "sec_per_step": 2.695, "max_mem_gb": 5.709}
{"loss": 0.3466, "aux_per_layer": 0.0, "grad_norm": 1.013, "step": 41, "lr": 0.0001963, "sec_per_step": 2.596, "max_mem_gb": 5.709}
{"loss": 0.3618, "aux_per_layer": 0.0, "grad_norm": 1.608, "step": 51, "lr": 0.0001921, "sec_per_step": 3.016, "max_mem_gb": 5.709}
{"loss": 0.4252, "aux_per_layer": 0.0, "grad_norm": 1.136, "step": 61, "lr": 0.0001863, "sec_per_step": 2.78, "max_mem_gb": 5.709}
{"loss": 0.2691, "aux_per_layer": 0.0, "grad_norm": 0.8056, "step": 71, "lr": 0.000179, "sec_per_step": 2.36, "max_mem_gb": 5.709}
{"loss": 0.2167, "aux_per_layer": 0.0, "grad_norm": 0.8496, "step": 81, "lr": 0.0001705, "sec_per_step": 2.646, "max_mem_gb": 5.829}
{"loss": 0.2507, "aux_per_layer": 0.0, "grad_norm": 0.8353, "step": 91, "lr": 0.0001609, "sec_per_step": 2.393, "max_mem_gb": 5.829}
{"loss": 0.07886, "aux_per_layer": 0.0, "grad_norm": 0.3895, "step": 101, "lr": 0.0001503, "sec_per_step": 2.975, "max_mem_gb": 5.829}
{"loss": 0.2092, "aux_per_layer": 0.0, "grad_norm": 0.5624, "step": 111, "lr": 0.000139, "sec_per_step": 2.942, "max_mem_gb": 5.829}
{"loss": 0.1848, "aux_per_layer": 0.0, "grad_norm": 0.7187, "step": 121, "lr": 0.0001271, "sec_per_step": 2.594, "max_mem_gb": 5.829}
{"loss": 0.255, "aux_per_layer": 0.0, "grad_norm": 0.7234, "step": 131, "lr": 0.0001149, "sec_per_step": 2.737, "max_mem_gb": 5.829}
{"loss": 0.1639, "aux_per_layer": 0.0, "grad_norm": 0.8712, "step": 141, "lr": 0.0001026, "sec_per_step": 2.863, "max_mem_gb": 5.829}
{"loss": 0.322, "aux_per_layer": 0.0, "grad_norm": 0.864, "step": 151, "lr": 9.049e-05, "sec_per_step": 2.855, "max_mem_gb": 5.829}
{"loss": 0.1965, "aux_per_layer": 0.0, "grad_norm": 0.7823, "step": 161, "lr": 7.871e-05, "sec_per_step": 3.114, "max_mem_gb": 5.829}
{"loss": 0.1931, "aux_per_layer": 0.0, "grad_norm": 0.657, "step": 171, "lr": 6.751e-05, "sec_per_step": 2.578, "max_mem_gb": 5.829}
{"loss": 0.4049, "aux_per_layer": 0.0, "grad_norm": 1.332, "step": 181, "lr": 5.71e-05, "sec_per_step": 2.743, "max_mem_gb": 5.829}
{"loss": 0.1082, "aux_per_layer": 0.0, "grad_norm": 0.533, "step": 191, "lr": 4.768e-05, "sec_per_step": 2.873, "max_mem_gb": 5.829}
{"loss": 0.128, "aux_per_layer": 0.0, "grad_norm": 0.4878, "step": 201, "lr": 3.942e-05, "sec_per_step": 2.485, "max_mem_gb": 5.829}
{"loss": 0.1886, "aux_per_layer": 0.0, "grad_norm": 0.6141, "step": 211, "lr": 3.247e-05, "sec_per_step": 2.409, "max_mem_gb": 5.829}
{"loss": 0.1235, "aux_per_layer": 0.0, "grad_norm": 0.4706, "step": 221, "lr": 2.697e-05, "sec_per_step": 2.386, "max_mem_gb": 5.829}
{"loss": 0.2507, "aux_per_layer": 0.0, "grad_norm": 0.6972, "step": 231, "lr": 2.301e-05, "sec_per_step": 3.16, "max_mem_gb": 5.829}
{"loss": 0.1812, "aux_per_layer": 0.0, "grad_norm": 0.6165, "step": 241, "lr": 2.068e-05, "sec_per_step": 2.371, "max_mem_gb": 5.829}
{"loss": 0.2129, "aux_per_layer": 0.0, "grad_norm": 0.7592, "step": 250, "lr": 2e-05, "sec_per_step": 2.984, "max_mem_gb": 5.829}

wandb: updating run metadata

{'val_loss': 0.17092676787336275, 'chrf': 92.9247225973617, 'exact_match': 0.43666666666666665, 'trainable': 117712896, 'active': 117712896, 'steps': 250, 'sec_per_step': 2.589542023989619, 'peak_mem_gb': 5.8294758796691895}

wandb:
wandb: Run history:
wandb: train/aux_per_layer ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     train/grad_norm █▃▃▁▃▂▂▂▃▄▂▂▂▂▂▂▂▁▂▂▁▂▁▃▂▂▂▂▁▂▂▂▂▃▂▂▁▂▂▁
wandb:          train/loss ▆▇▆▄▄▄█▇▅▂▂▄▄▄▄▆▃▄▅▃▃▄▂▂▄▁▅▅▇▂▅▃▅▄▆▁▂▂▅▃
wandb:            train/lr ▁▃▆▇█████▇▇▇▇▇▆▆▆▆▆▆▅▅▅▅▅▄▄▄▄▃▃▃▂▂▂▁▁▁▁▁
wandb:    train/max_mem_gb ▁▃▆▆▆▆▆▆▆▆▆▆▆▆▆█████████████████████████
wandb:  train/sec_per_step ▄▄▁█▄▃▆▄▅▄▂▄▅▇▂▅▁▇▄▇▃▆▃▂▅▆▄█▅█▅▅▂▆▅▃▄▄█▄
wandb:
wandb: Run summary:
wandb:              active 117712896
wandb:                chrf 92.92472
wandb:         exact_match 0.43667
wandb:         peak_mem_gb 5.82948
wandb:        sec_per_step 2.58954
wandb:               steps 250
wandb: train/aux_per_layer 0
wandb:     train/grad_norm 0.75918
wandb:          train/loss 0.21286
wandb:            train/lr 2e-05
wandb:                  +4 ...
wandb:
wandb: 🚀 View run lora-r102 at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/bl0n1jjl
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_163124-bl0n1jjl/logs
wandb: setting up run s8v5u3bq
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_164451-s8v5u3bq
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r29
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/s8v5u3bq

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{"loss": 0.2625, "aux_per_layer": 0.0, "grad_norm": 1.907, "step": 1, "lr": 2e-05, "sec_per_step": 2.765, "max_mem_gb": 3.858}
{"loss": 0.3182, "aux_per_layer": 0.0, "grad_norm": 0.9323, "step": 11, "lr": 0.00012, "sec_per_step": 2.426, "max_mem_gb": 4.209}
{"loss": 0.2554, "aux_per_layer": 0.0, "grad_norm": 0.6406, "step": 21, "lr": 0.0002, "sec_per_step": 2.477, "max_mem_gb": 4.311}
{"loss": 0.2607, "aux_per_layer": 0.0, "grad_norm": 0.6178, "step": 31, "lr": 0.000199, "sec_per_step": 2.59, "max_mem_gb": 4.445}
{"loss": 0.3294, "aux_per_layer": 0.0, "grad_norm": 0.6016, "step": 41, "lr": 0.0001963, "sec_per_step": 2.473, "max_mem_gb": 4.445}
{"loss": 0.3455, "aux_per_layer": 0.0, "grad_norm": 0.941, "step": 51, "lr": 0.0001921, "sec_per_step": 2.899, "max_mem_gb": 4.445}
{"loss": 0.3774, "aux_per_layer": 0.0, "grad_norm": 0.6837, "step": 61, "lr": 0.0001863, "sec_per_step": 2.7, "max_mem_gb": 4.445}
{"loss": 0.2524, "aux_per_layer": 0.0, "grad_norm": 0.4917, "step": 71, "lr": 0.000179, "sec_per_step": 2.263, "max_mem_gb": 4.445}
{"loss": 0.2212, "aux_per_layer": 0.0, "grad_norm": 0.5792, "step": 81, "lr": 0.0001705, "sec_per_step": 2.523, "max_mem_gb": 4.565}
{"loss": 0.2233, "aux_per_layer": 0.0, "grad_norm": 0.6092, "step": 91, "lr": 0.0001609, "sec_per_step": 2.292, "max_mem_gb": 4.565}
{"loss": 0.07675, "aux_per_layer": 0.0, "grad_norm": 0.2274, "step": 101, "lr": 0.0001503, "sec_per_step": 2.843, "max_mem_gb": 4.565}
{"loss": 0.2007, "aux_per_layer": 0.0, "grad_norm": 0.3711, "step": 111, "lr": 0.000139, "sec_per_step": 2.835, "max_mem_gb": 4.565}
{"loss": 0.1699, "aux_per_layer": 0.0, "grad_norm": 0.4479, "step": 121, "lr": 0.0001271, "sec_per_step": 2.687, "max_mem_gb": 4.565}
{"loss": 0.2475, "aux_per_layer": 0.0, "grad_norm": 0.4775, "step": 131, "lr": 0.0001149, "sec_per_step": 2.608, "max_mem_gb": 4.565}
{"loss": 0.1638, "aux_per_layer": 0.0, "grad_norm": 0.6417, "step": 141, "lr": 0.0001026, "sec_per_step": 2.748, "max_mem_gb": 4.565}
{"loss": 0.3148, "aux_per_layer": 0.0, "grad_norm": 0.5462, "step": 151, "lr": 9.049e-05, "sec_per_step": 2.738, "max_mem_gb": 4.565}
{"loss": 0.2076, "aux_per_layer": 0.0, "grad_norm": 0.4615, "step": 161, "lr": 7.871e-05, "sec_per_step": 2.99, "max_mem_gb": 4.565}
{"loss": 0.1789, "aux_per_layer": 0.0, "grad_norm": 0.3995, "step": 171, "lr": 6.751e-05, "sec_per_step": 2.429, "max_mem_gb": 4.565}
{"loss": 0.3856, "aux_per_layer": 0.0, "grad_norm": 0.7343, "step": 181, "lr": 5.71e-05, "sec_per_step": 2.611, "max_mem_gb": 4.565}
{"loss": 0.1077, "aux_per_layer": 0.0, "grad_norm": 0.4388, "step": 191, "lr": 4.768e-05, "sec_per_step": 2.761, "max_mem_gb": 4.565}
{"loss": 0.1288, "aux_per_layer": 0.0, "grad_norm": 0.3976, "step": 201, "lr": 3.942e-05, "sec_per_step": 2.367, "max_mem_gb": 4.565}
{"loss": 0.1842, "aux_per_layer": 0.0, "grad_norm": 0.4305, "step": 211, "lr": 3.247e-05, "sec_per_step": 2.296, "max_mem_gb": 4.565}
{"loss": 0.1252, "aux_per_layer": 0.0, "grad_norm": 0.3133, "step": 221, "lr": 2.697e-05, "sec_per_step": 2.261, "max_mem_gb": 4.565}
{"loss": 0.2696, "aux_per_layer": 0.0, "grad_norm": 0.5371, "step": 231, "lr": 2.301e-05, "sec_per_step": 3.042, "max_mem_gb": 4.565}
{"loss": 0.1904, "aux_per_layer": 0.0, "grad_norm": 0.5841, "step": 241, "lr": 2.068e-05, "sec_per_step": 2.255, "max_mem_gb": 4.565}
{"loss": 0.2273, "aux_per_layer": 0.0, "grad_norm": 0.6034, "step": 250, "lr": 2e-05, "sec_per_step": 2.87, "max_mem_gb": 4.565}

wandb: updating run metadata

{'val_loss': 0.1750112412135504, 'chrf': 92.78671822278308, 'exact_match': 0.42, 'trainable': 33467392, 'active': 33467392, 'steps': 250, 'sec_per_step': 2.4746897746105585, 'peak_mem_gb': 4.565489292144775}

wandb: uploading history steps 249-249, summary, console lines 26-26
wandb:
wandb: Run history:
wandb: train/aux_per_layer ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     train/grad_norm ██▁▅▄▆▃▁▄▂▄▄▁▃▄▄▂▁▅▆▄▄▂▄▃▃▅▇▃▁▂▅▆▅▃▄▂█▁▄
wandb:          train/loss ▆█▅▆▆▄▆▄▆▄▇▂▄▂▄▃▄▃▄▃▂▃▃▃▆▄▃▆▄▅▅▂▂▄▆▃▄▁▅▄
wandb:            train/lr ▂▅████████▇▇▇▇▇▇▇▆▆▆▆▆▆▆▆▅▅▄▄▃▂▂▂▂▂▁▁▁▁▁
wandb:    train/max_mem_gb ▁▄▅▅▅▇▇▇▇▇▇▇▇▇██████████████████████████
wandb:  train/sec_per_step ▂▂▅▂▃▅▂▃▂▄▄▃▅▅▄▂▇▃▅▆▃▃▆▅▇█▄▁▄▅▁▅▅▄▆▄█▇▄▃
wandb:
wandb: Run summary:
wandb:              active 33467392
wandb:                chrf 92.78672
wandb:         exact_match 0.42
wandb:         peak_mem_gb 4.56549
wandb:        sec_per_step 2.47469
wandb:               steps 250
wandb: train/aux_per_layer 0
wandb:     train/grad_norm 0.60343
wandb:          train/loss 0.22734
wandb:            train/lr 2e-05
wandb:                  +4 ...
wandb:
wandb: 🚀 View run lora-r29 at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/s8v5u3bq
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_164451-s8v5u3bq/logs

In [11]:
report = Part3Report(p3_dir, ["base", *RUNS])
start_run("summary", "analysis")
table = report.table()
report.routing_figures()
report.loss_curves()
wl.finish()
table

wandb: setting up run g1hmd2q2
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /kaggle/working/wandb/run-20261013_165745-g1hmd2q2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run summary
wandb: ⭐️ View project at https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: 🚀 View run at https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/g1hmd2q2
wandb: updating run metadata
wandb: uploading history steps 0-5, summary
wandb: 🚀 View run summary at: https://wandb.ai/ai340-nlp/ai500-lab1-part3/runs/g1hmd2q2
wandb: ⭐️ View project at: https://wandb.ai/ai340-nlp/ai500-lab1-part3
wandb: Synced 4 W&B file(s), 6 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20261013_165745-g1hmd2q2/logs

,run,chrF,EM,val_loss,trainable_M,active_M,sec_per_step,peak_mem_gb,maxvio_mean
0,base,55.456977,0.003333,0.403394,0.000000,0.000000,NaN,NaN,NaN
1,mixlora-none,92.991792,0.420000,0.175274,117.555200,32.915456,4.374766,7.643589,1.736614
2,mixlora-aux,92.551749,0.413333,0.174678,117.555200,32.915456,4.288287,7.616358,0.054328
3,mixlora-bias,92.828058,0.430000,0.175275,117.555200,32.915456,4.330522,7.613243,0.947275
4,lora-r16,92.669192,0.413333,0.177333,18.464768,18.464768,2.362030,4.341933,NaN
5,lora-r102,92.924723,0.436667,0.170927,117.712896,117.712896,2.589542,5.829476,NaN
6,lora-r29,92.786718,0.420000,0.175011,33.467392,33.467392,2.474690,4.565489,NaN